### ISSUE TITLE
Following hoplon Getting Started, fails on Step 2

### ISSUE THREAD

**Issue by rohni** [tailrecursion/hoplon#50]
Hi there,
I was really excited to try out hoplon, but ran into this snag:

     Task 2: Compile the project.

     $ boot development

However, this fails with:

    java.lang.RuntimeException: No reader function for tag tailrecursion.boot.core/version

I tried upgrading boot:

    Retrieving boot-2.0.0-rc4.jar from http://clojars.org/repo/
    #https://github.com/boot-clj/boot
    #Thu Jan 01 01:58:12 CET 2015
    BOOT_CLOJURE_VERSION=1.6.0
    BOOT_VERSION=2.0.0-rc4

But just received the same error.

I am stuck, and in need of sleep. :)  If anyone can figure out what is going wrong here I would love to move onto exploring hoplon.

Thanks,

Rohni

**Comment by rohni** [comment]
The boot-cljs/boot demo was also borking with boot-2.0.0-rc4, so ran it with this:

Thought I would try using the dev version and see if that worked:
```bash
BOOT_CHANNEL='DEV' boot --update
```
Which gave this output:

```
#https://github.com/boot-clj/boot
#Thu Jan 01 09:28:04 CET 2015
BOOT_CLOJURE_VERSION=1.6.0
BOOT_VERSION=2.0.0-pre28
```
So I followed the boot tutorial to the next step

```bash
boot serve -d target/ watch speak cljs-repl cljs -usO none reload
```
Which worked. :)  Flushed with this success I tried the same in hoplon:

```bash
BOOT_CHANNEL='DEV' boot development
```
Which still wanted that reader function:
```
java.lang.RuntimeException: No reader function for tag tailrecursion.boot.core/version
                      ...
clojure.core/read-string  core.clj: 3497
boot.util/read-string-all  util.clj:  134
boot.main/-main  main.clj:  104
               ...
boot.App.runBoot  App.java:  225
boot.App.main  App.java:  317
```

**Comment by alandipert** [comment]
Hi, sorry that you're having difficulties!  The problem is that the Hoplon tutorials assume you're using boot 1, at [tailrecursion/boot](https://github.com/tailrecursion/boot).

Unfortunately we haven't ported Hoplon too boot 2 - the one at boot-clj/boot - yet, so if you want to both use hoplon and boot 2, you need to have booth boots installed.

Personally I have boot 1 installed as 'boot1' on my system, that way I can do `boot1 development` etc.

Sorry for the confusion!  We'll have Hoplon ported to boot2 soon and then this will stop being confusing.

**Comment by rohni** [comment]
Thank-you very much.  That solved the problem.  
I was just trying to be too clever and use the latest and greatest.  Serve me right. :)
